Sys.setlocale("LC_TIME", "English")
data<-read.table("household_power_consumption.txt", stringsAsFactors = F,sep = ";", h=T)
datetime<-paste(data$Date,data$Time)
changeddate<-as.POSIXct(strptime(datetime,"%d/%m/%Y %H:%M:%S"))
data<-cbind(changeddate,data[,-(1:2)])
dat<-subset(data,changeddate >= as.POSIXct("2007-02-01 00:00:00 PST") & changeddate < as.POSIXct("2007-02-02 23:59:59 PST") )
dat$Sub_metering_1<-as.numeric(as.character(dat$Sub_metering_1))
dat$Sub_metering_2<-as.numeric(as.character(dat$Sub_metering_2))
dat$Sub_metering_3<-as.numeric(as.character(dat$Sub_metering_3))
dat$Global_active_power<-as.numeric(as.character(dat$Global_active_power))
dat$Global_reactive_power<-as.numeric(as.character(dat$Global_reactive_power))
dat$Voltage<-as.numeric(as.character(dat$Voltage))
png("plot4.png",width=480,height=480)
par(mfrow=c(2,2))
plot(dat$Global_active_power ~ dat$changeddate,type="l",xlab="",ylab="Global Active Power")
plot(dat$Voltage ~ dat$changeddate,type="l",xlab="datetime",ylab="Voltage")
plot(dat$Sub_metering_1 ~ dat$changeddate,type="n",xlab="",ylab="Energy sub metering")
lines(dat$Sub_metering_1 ~ dat$changeddate,xlab="",ylab="Energy sub metering")
lines(dat$Sub_metering_2 ~ dat$changeddate,xlab="",ylab="Energy sub metering",col="red")
lines(dat$Sub_metering_3 ~ dat$changeddate,xlab="",ylab="Energy sub metering",col="blue")
legend("topright",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,bty="n")
plot(dat$Global_reactive_power ~ dat$changeddate,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()