Sys.setlocale("LC_TIME", "English")
data<-read.table("household_power_consumption.txt", stringsAsFactors = F,sep = ";", h=T)
datetime<-paste(data$Date,data$Time)
changeddate<-as.POSIXct(strptime(datetime,"%d/%m/%Y %H:%M:%S"))
data<-cbind(changeddate,data[,-(1:2)])
dat<-subset(data,changeddate >= as.POSIXct("2007-02-01 00:00:00 PST") & changeddate < as.POSIXct("2007-02-02 23:59:59 PST") )
dat$Global_active_power<-as.numeric(as.character(dat$Global_active_power))
png("plot2.png",width=480,height=480)
plot(dat$Global_active_power ~ dat$changeddate,type="l",xlab="",ylab="Global Active Power (kilowatts)")
dev.off()